#
# meta-rootfs-enc-core/conf/layer.conf
#
# Root filesystem encryption layer configuration (core/base)
#
# Copyright (c) 1983-2026 Advantech Co., Ltd. All rights reserved.
#

BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"
BBFILE_COLLECTIONS += "meta-rootfs-enc-core"
BBFILE_PATTERN_meta-rootfs-enc-core = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-rootfs-enc-core = "10"
LAYERVERSION_meta-rootfs-enc-core = "1"
LAYERSERIES_COMPAT_meta-rootfs-enc-core = "scarthgap styhead walnascar whinlatter wrynose blacksail"
