#
# meta-secure-boot-nxp/conf/layer.conf
#
# Secure Boot layer for i.MX NXP systems
#
# Copyright (c) 1983-2026 Advantech Co., Ltd. All rights reserved.
#

BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"
BBFILE_COLLECTIONS += "meta-secure-boot-nxp"
BBFILE_PATTERN_meta-secure-boot-nxp = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-secure-boot-nxp = "9"
LAYERVERSION_meta-secure-boot-nxp = "1"
LAYERSERIES_COMPAT_meta-secure-boot-nxp = "scarthgap styhead walnascar whinlatter wrynose blacksail"
